# Generated by Django 4.2.7 on 2025-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_fix_rtsp_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='thumbnail_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
